# Generated by Django 6.0.4 on 2026-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='TSJbBSFjiD1ahMcmCBtEdHgIUsQjwSBH', editable=False, max_length=32, unique=True),
        ),
    ]
