# Generated by Django 6.0.4 on 2026-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ytePkLSAKLBzSy9MHs34mqB3JgJWkVB9', editable=False, max_length=32, unique=True),
        ),
    ]
