# Generated by Django 6.0.4 on 2026-04-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='B3qpDqvdRE7Gu78dVPbj2eHeMTKXIJD7', editable=False, max_length=32, unique=True),
        ),
    ]
