# Generated by Django 6.0.4 on 2026-04-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='dKrdS84Uo0qrQAu7utNJl2p2EYpkJeG4', editable=False, max_length=32, unique=True),
        ),
    ]
