# Generated by Django 6.0.4 on 2026-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='aFrRi5beohs3YDnZ4WTxe91ib4IDOQac', editable=False, max_length=32, unique=True),
        ),
    ]
