# Generated by Django 6.0.4 on 2026-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gJIV3UJIbZB5CtBVIHpEGp3frGAwJ1Qx', editable=False, max_length=32, unique=True),
        ),
    ]
