# Generated by Django 6.0.4 on 2026-04-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='a0Rzh5Bd9OBwjJ1gDZT8DvhjgA4OUbAD', editable=False, max_length=32, unique=True),
        ),
    ]
