# Generated by Django 6.0.4 on 2026-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='nFwBJSBa53CsTWu8BUgbuiWx2xUTHc8H', editable=False, max_length=32, unique=True),
        ),
    ]
